version: "3.8"

services:
  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - microservices-network
    restart: unless-stopped

  api-gateway:
    build: .
    container_name: api-gateway
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
    command: python app/api_gateway/gateway.py
    networks:
      - microservices-network
    volumes:
      - sqlite-data:/data
    restart: unless-stopped

  celery-worker:
    build: .
    container_name: celery-worker
    ports:
      - "5005:5005"
    command: python app/worker/start_worker.py
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - SQLITE_DB_PATH=/data/operations.db
    depends_on:
      - redis
    networks:
      - microservices-network
    volumes:
      - sqlite-data:/data
    restart: unless-stopped

  reserves-service:
    build: .
    container_name: reserves-service
    ports:
      - "5001:5001"
    environment:
      - FLASK_ENV=development
    command: python app/services/reserves/reserves.py
    networks:
      - microservices-network
    restart: unless-stopped

  payments-service:
    build: .
    container_name: payments-service
    ports:
      - "5002:5002"
    environment:
      - FLASK_ENV=development
    command: python app/services/payments/payments.py
    networks:
      - microservices-network
    restart: unless-stopped

  search-service:
    build: .
    container_name: search-service
    ports:
      - "5003:5003"
    environment:
      - FLASK_ENV=development
    command: python app/services/search/search.py
    networks:
      - microservices-network
    restart: unless-stopped

  monitor:
    build: .
    container_name: monitor
    ports:
      - "5006:5006"
    command: python app/monitor/start_monitor.py
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - SQLITE_DB_PATH=/data/operations.db
    depends_on:
      - redis
      - celery-worker
      - api-gateway
      - reserves-service
      - payments-service
      - search-service
    networks:
      - microservices-network
    volumes:
      - sqlite-data:/data
      - /var/run/docker.sock:/var/run/docker.sock  # Para recovery autom√°tico
    restart: unless-stopped

networks:
  microservices-network:
    driver: bridge

volumes:
  sqlite-data:
